# Generated by Django 4.1.7 on 2023-03-24 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_abbreviation', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
