# Generated by Django 4.1.7 on 2023-03-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Teacher'},
        ),
    ]
